#pragma config(Sensor, S1,     sColour,        sensorTouch)
#pragma config(Sensor, S2,     sCheck,         sensorTouch)
#pragma config(Sensor, S3,     sColor,         sensorColorNxtFULL)
#pragma config(Motor,  motorA,          mCon,          tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB,          mSort,         tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          mDoor,         tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int check_apple = 0;
int colour = 0;
task Con()
{
	while (true)
	{
		motor[mCon]= 20;
	}
}
void door2_open()
{
	nMotorEncoder[mSort]=0;
	while (nMotorEncoder[mSort] > -53)
	{
		motor[mSort]=-30;
	}
	motor[mSort]=0;
}

void door2_close()
{
	nMotorEncoder[mSort]=0;
	while (nMotorEncoder[mSort] < 53)
	{
		motor[mSort]=30;
	}
	motor[mSort]=0;
}
void door_open()
{
	while (nMotorEncoder[mDoor] < 100)
	{
		motor[mDoor]=30;

	}
	motor[mDoor]=0 ;
	nMotorEncoder[mDoor]=0;

}
void door_close()
{
	nMotorEncoder[mDoor]=0;
	while (nMotorEncoder[mDoor] > -100)
	{
		motor[mDoor]=-30;

	}
	motor[mDoor]=0 ;
	nMotorEncoder[mDoor]=0;

}

task Check_Apple ()
{
	displayTextLine(3, "%d", check_apple);
	while (true)
	{
		if (SensorValue[sCheck]!=0)
		{
			if (check_apple == 0)
			{
				check_apple = 1;
				playSound(soundLowBuzz);
				wait1Msec(1000);
			}
			else
			{
				check_apple = 0;
				playSound(soundBeepBeep);
				wait1Msec(1000);
			}

		}
		displaybigTextLine(3, "%d", check_apple);
	}
}


task main()
{

	startTask (Check_Apple);
	startTask (Con);
	while (true)
	{
		colour = 1;

		while (SensorValue[sColour]<=0)// dlya testa
		{
			wait1Msec(10);
		}
		if (check_apple== 0)
		{
			wait1Msec(1000);
			if (SensorValue[sColour] == 0)//red
			{
				colour = 0	; //red

				door2_open ();
				door_open ();

				wait1Msec(5000);

				door_close ();
				wait1Msec(5000);
				door2_close();

			}
			else //  colour =0 yellow
			{
				door_open ();
				wait1Msec(5000);
				playSound(soundBeepBeep);
				door_close ();

			}

			displaybigTextLine(6, "%d", colour);


		}
		else
		{
			playSound(soundDownwardTones);
			wait1Msec(1000);
			check_apple = 0;
		}
	}
}
