#pragma config(Sensor, S1,     sColour,        sensorEV3_Color, modeEV3Color_Color)
#pragma config(Motor,  motorA,          mCon,          tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB,          mSort,         tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          mDoor,         tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int color = 0;

long redValue;
long greenValue;
long blueValue;
task Con()
{
	while (true)
	{
		motor[mCon]= 20; //run transporter
	}
}
void door2_open() //red or yellow
{
	nMotorEncoder[mSort]=0;
	while (nMotorEncoder[mSort] > -53)
	{
		motor[mSort]=-30;
	}
	motor[mSort]=0;
}

void door2_close()
{
	nMotorEncoder[mSort]=0;
	while (nMotorEncoder[mSort] < 53)
	{
		motor[mSort]=30;
	}
	motor[mSort]=0;
}
void door_open()
{
	while (nMotorEncoder[mDoor] < 100)
	{
		motor[mDoor]=30;

	}
	motor[mDoor]=0 ;
	nMotorEncoder[mDoor]=0;

}
void door_close()
{
	nMotorEncoder[mDoor]=0;
	while (nMotorEncoder[mDoor] > -100)
	{
		motor[mDoor]=-30;

	}
	motor[mDoor]=0 ;
	nMotorEncoder[mDoor]=0;

}
void colour()
{
	getColorRGB(sColour, redValue, greenValue, blueValue);
	setSensorMode(sColour,modeEV3Color_Color);
	while(redValue < 20)
	{
		getColorRGB(sColour, redValue, greenValue, blueValue);
		displayBigTextLine(2, "%f", redValue);
		displayBigTextLine(4, "%f", greenValue);
		displayBigTextLine(6, "%f", blueValue);
		sleep(100);
	}

}



task main()
{

	startTask (Con);
	while (true)
	{


		colour();

		wait1Msec(1000);
		if (greenValue > 50)
		{
			eraseDisplay();
			color = 1;
			displayBigTextLine(4,"%d" , color);
			sleep(1000);
			eraseDisplay();




			door2_open ();
			door_open ();

			wait1Msec(5000);

			door_close ();
			wait1Msec(5000);
			door2_close();

		}
		else
		{

			eraseDisplay();
			color= 0;
			displayBigTextLine(4,"%d" , color);
			eraseDisplay();
			door_open ();
			wait1Msec(5000);
			playSound(soundBeepBeep);
			door_close ();

		}
	}
}
