#pragma config(Sensor, S1,     sM_cour,        sensorEV3_GenericI2C)
#pragma config(Sensor, S2,     sTrans,         sensorSONAR)
#pragma config(Sensor, S3,     sApple,         sensorEV3_IRSensor)
#pragma config(Sensor, S4,     sColour,        sensorEV3_Color)
#pragma config(Motor,  motorA,          mPush,         tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB,          mSort,         tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          mDoor,         tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorD,          mCon,          tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "mindsensors-ev3smux.h"

int const DISTANCE_TO_COURIER = 20;//dis to courier
int const DISTANCE_TO_TRANSPORTER = 20;//dist no transporter
int const DISTANCE_WITHOUT_APPLE = 25;//distance without apple
int const MAX_DISTANCE_2_BIG_APPLE = 21;
int const GREEN = 0;
int const RED = 1;
int const SMALL = 0;
int const BIG = 1;
// The SMUX can have up to 3 sensors attached to it.
tMSEV3 muxedSensor[1];
tEV3SensorTypeMode typeMode[1] = {infraRedProximity};
// int color = 0;
int appleColorNow = GREEN;
int appleSizeNow = SMALL;
int isAppleLoaderLoading = 0;
bool isAppleReady4Conveyer = 0;//0- no apple near RGB, 1 - apple arrived
bool isCourierHere = 0;
bool isAppleLoaderUp = 0;
bool isTransporterHere = 0;
bool determineByColor = 0;//dis=0,col=1
//min dis to big apple
float currentDistance2Apple = 0;//value from sensor to check that apple appear near RGB




task Con()
{
	while (true)
	{
		if (isCourierHere == 1)
		{
			motor[mCon]= 20; //run conveer
		}
		else
		{
			motor[mCon]= 0;
		}
	}
}

/*task colour()
{
getColorRGB(sColour, redValue, greenValue, blueValue);
setSensorMode(sColour,modeEV3Color_Color);
while(true)
{
getColorRGB(sColour, redValue, greenValue, blueValue);
displayTextLine(4, "%f", redValue);
displayTextLine(5, "%f", greenValue);
displayTextLine(6, "%f", blueValue);
sleep(100);
}
}*/
void door2_open() //red or green
{
	nMotorEncoder[mSort]=0;
	while (nMotorEncoder[mSort] > -53)
	{
		motor[mSort]=-30;
	}
	motor[mSort]=0;
}

void door2_close()
{
	nMotorEncoder[mSort]=0;
	while (nMotorEncoder[mSort] < 53)
	{
		motor[mSort]=30;
	}
	motor[mSort]=0;
}
/*void door_open()
{
while (nMotorEncoder[mDoor] < 100)
{
motor[mDoor]=30;

}
motor[mDoor]=0 ;
nMotorEncoder[mDoor]=0;

}
void door_close()
{
nMotorEncoder[mDoor]=0;
while (nMotorEncoder[mDoor] > -100)
{
motor[mDoor]=-30;

}
motor[mDoor]=0 ;
nMotorEncoder[mDoor]=0;
}
*/
task dis_col() //check apple near RGB
{
	while(true)
	{
		//readSensor(&muxedSensor[1]);
		currentDistance2Apple = SensorValue[sApple];
		displayTextLine(9,"dv = %d",currentDistance2Apple);
		displayTextLine(10," df = %d",isAppleReady4Conveyer);
		if (SensorValue[sApple]>-255)
		{
			if (currentDistance2Apple < DISTANCE_WITHOUT_APPLE)
			{
				isAppleReady4Conveyer = 1;
			}
			else
			{
				isAppleReady4Conveyer = 0;
			}
		}
		else
		{
			isAppleReady4Conveyer = 0;
		}
		sleep(100);
	}
}
task trans()//check trasportrer near
{
	while(true)
	{
		int a = 0;
		a = SensorValue[sTrans];
		displayTextLine(13, "a = %d", a);
		displayTextLine(0,"ft= %d",isTransporterHere);
		if (SensorValue[sTrans] <DISTANCE_TO_TRANSPORTER)
		{
			sleep(1000);
			if (SensorValue[sTrans]<DISTANCE_TO_TRANSPORTER)
			{
				isTransporterHere = 1;
			}
			else
			{
				isTransporterHere = 0;
			}
		}
		else
		{
			isTransporterHere = 0;
		}
	}
}
int getSize()
{
	int a1 = SensorValue[sApple];
	sleep(1000);
	int a2 = SensorValue[sApple];
	sleep(1000);
	int a3 = SensorValue[sApple];
	float dist =(a1+a2+a3)/3;
	int appleSize = 0;
	if (dist < MAX_DISTANCE_2_BIG_APPLE)
	{
		appleSize = BIG;
	}
	else
	{
		appleSize = SMALL;
	}
	return appleSize;
}
int getColour()
{
	long greenValue1;
	long blueValue1;
	long redValue1;
	long greenValue2;
	long blueValue2;
	long redValue2;
	long greenValue3;
	long blueValue3;
	long redValue3;
	getColorRGB(sColour, redValue1, greenValue1, blueValue1);
	sleep(1000);
	getColorRGB(sColour, redValue2, greenValue2, blueValue2);
	sleep(1000);
	getColorRGB(sColour, redValue3, greenValue3, blueValue3);
	float redValue = (redValue1+redValue2+redValue3)/3;
	float greenValue = (greenValue1+greenValue2+greenValue3)/3;
	float blueValue = (blueValue1+blueValue2+blueValue3)/3;
	int col = GREEN;
	if ((redValue > 5)&&(greenValue<5 ))//****
	{
		col = RED;
	}
	else
	{
		col = GREEN;
	}
	return col;
}
task cours()//check courier is near
{
	while(true)
	{

		readSensor(&muxedSensor[0]);
		//		readSensor(&muxedSensor[1]);
		displayTextLine(12, "Distance: %d", muxedSensor[0].distance);
		//	displayTextLine(13, "Distance: %d", muxedSensor[1].distance);
		sleep(200);
		if (muxedSensor[0].distance >DISTANCE_TO_COURIER)
		{
			isCourierHere = 0;
		}
		else
		{
			isCourierHere = 1;
		}

	}
}
void appToConBack()//close pusher
{
	//displayTextLine(1,"p = %d", nMotorEncoder[mPush])
	nMotorEncoder[mPush]=0;
	while ( nMotorEncoder[mPush]<370)
	{
		motor[mPush]=50;
		sleep(1);
	}
	motor[mPush]=0;
}
void appToCon()//open pusher
{
	nMotorEncoder[mPush]=0;
	while ( nMotorEncoder[mPush]>-370)
	{
		//displayTextLine(1,"p = %d", nMotorEncoder[mPush])
		motor[mPush]=-50;
		sleep(1);
	}
	motor[mPush]=0;
}
void appToConBack2()//close pusher
{
	//displayTextLine(1,"p = %d", nMotorEncoder[mPush])
	nMotorEncoder[mPush]=0;
	while ( nMotorEncoder[mPush]<250)
	{
		motor[mPush]=50;
		sleep(1);
	}
	motor[mPush]=0;
}
void appToCon2()//open pusher
{
	nMotorEncoder[mPush]=0;
	while ( nMotorEncoder[mPush]>-250)
	{
		//displayTextLine(1,"p = %d", nMotorEncoder[mPush])
		motor[mPush]=-50;
		sleep(1);
	}
	motor[mPush]=0;
}
void moveAppleToBascet()
{
	appToConBack2();
	sleep(2000);
	appToCon2();
	sleep(2000);
	door2_open();
	sleep(5000);
	door2_close();
}
void moveAppleToCourier()
{
	appToConBack();
	sleep(2000);
	appToCon();
}
//---------------------------------------------------------------------------------------------------------------------------------------------
task main()
{
	initSensor(&muxedSensor[0], msensor_S1_1, typeMode[0]);

	startTask(cours);
	startTask(dis_col);
	startTask(trans);
	while(true)
	{
		displayTextLine(4,"S = %d",appleSizeNow);
		displayTextLine(5,"C = %d",appleColorNow);
		if (isAppleLoaderUp == 0)
		{
		if(isTransporterHere == 1)
		{
			while (isTransporterHere == 1)//is there transporter or no
			{
				sleep(100);
			}
			nMotorEncoder[mDoor]=0;
			while (nMotorEncoder[mDoor]>-350)//body up
			{
				motor[mDoor]=-15;

			}
			isAppleLoaderUp = 1;
			motor[mDoor]=0;
			isAppleLoaderLoading = 1;
			startTask(Con);
		}
	}
		if (determineByColor == 0)
		{
			if (isAppleLoaderLoading == 1)
			{
				if(isAppleReady4Conveyer==1)
				{
					appleSizeNow = getSize();
					if (appleSizeNow == BIG)
					{
						moveAppleToCourier();
					}
					else
					{
						sleep(3000);
						if (appleSizeNow == SMALL)
						{
							moveAppleToBascet();
						}
					}
				}
				sleep(1);
			}
		}
		else // comparing by COLOUR
		{
			if (isAppleLoaderLoading == 1)
			{
				if(isAppleReady4Conveyer==1) // apple exist
				{
					appleSizeNow = getSize();
					if (appleSizeNow == BIG) // apple is big
					{
						appleColorNow=getColour();
						playSound(soundDownwardTones);
						sleep(1000);
						//playSound(soundDownwardTones);
						if(appleColorNow == RED) // apple is red
						{
							playSound(soundDownwardTones);
							appToConBack();
							sleep(2000);
							appToCon();
							//colorflag = 0;
							sleep(2000);
						}
						else
						{
							appToConBack();
							sleep(2000);
							appToCon();
							//colorflag = 0;
							door2_open();
							sleep(7000);
							door2_close();

						}
					}
					else // apple is small (and so it is red)
					{
						sleep(3000);
						if (appleSizeNow == SMALL)//double check that apple is really small
						{
							playSound(soundBeepBeep);
							appToConBack();
							sleep(2000);
							appToCon();
							sleep(2000);
						}
					}
				}
			}
		}
	}
}
