#pragma config(Sensor, S1,     sM_cour,        sensorEV3_GenericI2C)
#pragma config(Sensor, S2,     sTrans,         sensorSONAR)
#pragma config(Sensor, S3,     sApple,         sensorEV3_IRSensor)
#pragma config(Sensor, S4,     sColour,        sensorEV3_Color)
#pragma config(Motor,  motorA,          mPush,         tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB,          mSort,         tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          mDoor,         tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorD,          mCon,          tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "mindsensors-ev3smux.h"


// The SMUX can have up to 3 sensors attached to it.
tMSEV3 muxedSensor[1];
tEV3SensorTypeMode typeMode[1] = {infraRedProximity};
// int color = 0;

int flagT = 0;//0-no transporter, 1- transporter arrived conv start
int colOrDis = 0;//dis=0,col=1
long greenValue;
long blueValue;
long redValue;
float const disA2 = 23.5;//min dis to big apple
//int const min_for_green=8; //max for red 7, min for green 12 -green value
int colorflag = 0;// green =1, red = 0
int const disA = 26;//distance without apple
float disValue = 0;//value from sensor to check that apple appear near RGB
int disflag = 0;//0- no apple near RGB, 1 - apple arrived
int cour = 0;//0- 1 or 2 courier go out, 1- both couriers stands
int const courdis = 20;//dis to courier
int const transdis = 20;//dist no transporter
int getSize()
{
int a1 = SensorValue[sApple];
sleep(1000);
int a2 = SensorValue[sApple];
sleep(1000);
int a3 = SensorValue[sApple];
float dist =(a1+a2+a3)/3;
int size = 0;
if (dist < disA2)
{
size = 1;
}
else
{
size = 0;
}
return size;
}
int getColour()
{
	long greenValue1;
	long blueValue1;
	long redValue1;
	long greenValue2;
	long blueValue2;
	long redValue2;
	long greenValue3;
	long blueValue3;
	long redValue3;
	getColorRGB(sColour, redValue1, greenValue1, blueValue1);
	sleep(1000);
	getColorRGB(sColour, redValue2, greenValue2, blueValue2);
	sleep(1000);
	getColorRGB(sColour, redValue3, greenValue3, blueValue3);
	float redValue = (redValue1+redValue2+redValue3)/3
	float greenValue = (greenValue1+greenValue2+greenValue3)/3
	float blueValue = (blueValue1+blueValue2+blueValue3)/3
	int col = 0;
	if ((redValue > 5)&&(greenValue<5 ))
	{
		col = 1;
	}
	else
	{
		col = 0;
	}
	return col;
}
task main()
{


	while(true)
	{
		int a = getColour();
		int b = getSize();
		displayTextLine(1, "col = %d", a);
		displayTextLine(3, "size = %d", b);
		playSound(soundBeepBeep);
		sleep(1000);
	}
}
