#pragma config(Sensor, S2,     ,               sensorEV3_GenericI2C)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "mindsensors-ev3smux.h"


// The SMUX can have up to 3 sensors attached to it.
tMSEV3 muxedSensor[1];
tEV3SensorTypeMode typeMode[1] = {infraRedProximity};

task main()
{
	initSensor(&muxedSensor[0], msensor_S2_1, typeMode[0]);
	while(true)
	{
		readSensor(&muxedSensor[0]);
		displayTextLine(1, "Distance: %d", muxedSensor[0].distance);
		sleep(200);
	}
}
