#pragma config(Sensor, S1,     sIr,            sensorEV3_IRSensor)
#pragma config(Sensor, S2,     ,               sensorEV3_Touch)
#pragma config(Motor,  motorA,          mA,            tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorB,          mB,            tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorC,          mC,            tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorD,          mD,            tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	int e;
	while(true)
	{
	  e = getIRBeaconDirection(sIr);
	  displayBigTextLine(4, "%d",e)
		if ( e < 0)
		{
			motor[mA]=-20;
			motor[mB]=20;
			sleep(1);
		}
		else if ( e > 0)
		{
			motor[mA]=20;
			motor[mB]=-20;
			sleep(1);
		}
		else
		{
			motor[mA]=50;
			motor[mB]=50;
			sleep(1);
		}
	}
}
