#pragma config(Sensor, S1,     sIr,            sensorEV3_IRSensor)
#pragma config(Sensor, S2,     ,               sensorEV3_Touch)
#pragma config(Motor,  motorA,          mA,            tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorB,          mB,            tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorC,          mC,            tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorD,          mD,            tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	int e;
	//e = SensorValue[S2]
  e = getIRBeaconDirection(sIr);
	if ( e > 0)
	{
		motor[mA]=100;
		motor[mB]=100;
		sleep(2000);
	}
}
