#pragma config(Motor,  motorA,          mRunleft,      tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorB,          mRunright,     tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorC,          mOut,          tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorD,          mDoor,         tmotorEV3_Medium, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void dooro ()
{
	nMotorEncoder[mDoor]=0;
	while(nMotorEncoder[mDoor]<95)
	{
		motor[mDoor]=70;
		sleep(1);
	}

}
void doorc ()
{
	nMotorEncoder[mDoor]=0;
	while(nMotorEncoder[mDoor]>-95)
	{
		motor[mDoor]=-70;
		sleep(1);
	}
}
task main()
{
	nMotorEncoder[mOut]=0;
	while (nMotorEncoder[mOut]>-2500)
	{
		motor[mOut]= -100;

		wait1Msec(1);
	}
	motor[mOut]=0;
	dooro ();

	doorc();

		nMotorEncoder[mOut]=0;
	while (nMotorEncoder[mOut]<2500)
	{
		motor[mOut]=  100;

		wait1Msec(1);
	}

}
