#pragma config(Sensor, S1,     sSonar,         sensorSONAR)
#pragma config(Motor,  motorA,          mRunleft,      tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB,          mRunright,     tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          mOut,          tmotorNXT, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	const int S = 15;
	while(true)
	{
		if (SensorValue[sSonar] > S)
		{
			nMotorEncoder[mRunleft] = 0;
			while(nMotorEncoder[mRunleft]> -1)
			{
				motor[mRunleft]= -100;
				motor[mRunright]= -100;
			}
			motor[mRunleft]= 0;
			motor[mRunright]= 0;
			nMotorEncoder[mRunleft] = 0;
		}
		else
		{
			nMotorEncoder[mRunleft] = 0;
			while(nMotorEncoder[mRunleft]< 1)
			{
				motor[mRunleft]= 100;
				motor[mRunright]= 100;
			}
			motor[mRunleft]= 0;
			motor[mRunright]= 0;
			nMotorEncoder[mRunleft] = 0;

		}
	}
}
