#pragma config(Sensor, S1,     sIr,            sensorEV3_IRSensor, modeEV3IR_Seeker)
#pragma config(Sensor, S2,     sDis,           sensorEV3_IRSensor)
#pragma config(Sensor, S3,     sApple,         sensorSONAR)
#pragma config(Motor,  motorA,          mA,            tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorB,          mB,            tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorC,          mOut,          tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorD,          mDoor,         tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
int e = 0;
int apple = 0;
int n = 0;
int const v1 = 20; // nei?inou aey iiai?ioa
int	const v2 = 30; // nei?inou aey acau i?yii
int dis = 0;
int dis2 = 0;
int f = 0;
void dooro ()
{
	nMotorEncoder[mDoor]=0;
	while(nMotorEncoder[mDoor]<95)
	{
		motor[mDoor]=70;
		sleep(1);
	}

}
void doorc ()
{
	nMotorEncoder[mDoor]=0;
	while(nMotorEncoder[mDoor]>-95)
	{
		motor[mDoor]=-70;
		sleep(1);
	}
}
task distance() //?annoiyiea ai i?aiyonoaey
{
	while (true)
	{
		dis = SensorValue[sDis];
		displayTextLine(5,"%d",dis);
		if(SensorValue[sDis]<30)
		{
			if (SensorValue[sDis]<15)
			{
				n = 1; //oeaa inoaiiaee = noiyou
				f = 0;
			}
			else
			{
				n = 0;
				f = 0;

			}
		}
		else
		{
			n = 0;
			f = 1;
		}
	}
}
task apples()
{

	while(true)
	{
		dis2 = SensorValue[sApple];
		displayTextLine(6,"%d",apple);
		displayTextLine(7,"%d",dis2);
		if (SensorValue[sApple]<10)
		{
			sleep(2000);
			if (SensorValue[sApple]<10)
			{
				apple = 1;
			}
		}
		else
		{
			apple = 0;
		}
	}
}



task main()
{
	startTask(distance);
	startTask(apples);

	while(true)
	{
		if ( apple == 0)
		{
			if ( n == 0)
			{                                  // acaa ca eio?ae?aniui iayeii
				//e = getIRBeaconChannelDirection(sIr,2);
				e = getIRBeaconDirection(sIr);
				displayTextLine(4, "%d",e);
				if ( e > 2)
				{
					motor[mB]= -1 * v1;
					motor[mA]= v1;
					sleep(1);
				}
				else if ( e < -2)
				{
					motor[mB]=f*v1;
					motor[mA]= f*-1 * v1;
					sleep(1);
				}
				else
				{
					motor[mA]=f*v2;
					motor[mB]=f*v2;
					sleep(1);
				}
			}
			else
			{// neeoeii iaeaiueia ?annoiyiea, iaai iouaoaou
				motor[mB]=v2;
				motor[mA]=v2;
				sleep(1);
				nMotorEncoder[mB]=0;
				while (nMotorEncoder[mB]>-500)
				{
					motor[mB]=-50;
					motor[mA]=-50;
					sleep(1);
				}
			}
		}
		else
		{//aua?ocea yaeiea
			motor[mB]=v2;
			motor[mA]=v2;
			sleep(1);
			nMotorEncoder[mB]=0;
			while (nMotorEncoder[mB]>-500)
			{
				motor[mB]=-50;
				motor[mA]=-50;
				sleep(1);

			}
			motor[mB]=0;
			motor[mA]=0;
			nMotorEncoder[mOut]=0;
			while (nMotorEncoder[mOut]>-2500)
			{
				motor[mOut]= -100;

				wait1Msec(1);
			}
			motor[mOut]=0;
			dooro ();
			sleep(500);
			doorc();

			nMotorEncoder[mOut]=0;
			while (nMotorEncoder[mOut]<2500)
			{
				motor[mOut]=  100;

				wait1Msec(1);
			}
			motor[mOut]=0;


		}

	}

}
