#pragma config(Motor,  motorA,          mUp,           tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB,          mBuck,         tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while ( nMotorEncoder[mBuck]>-13000)
	{
		motor[mBuck] = -100;
	}
	motor[mBuck] = 0 ;
	nMotorEncoder[mBuck]= 0 ;
	nMotorEncoder[mUp]= 0;
	while ( nMotorEncoder[mUp]<6500)
	{
		motor[mUp] = 100;
	}
	motor[mUp] = 0 ;
	while ( nMotorEncoder[mBuck]>-2200)
	{
		motor[mBuck] = -100;
	}
	motor[mBuck] = 0 ;
	wait1Msec(20000);
	nMotorEncoder[mBuck]= 0 ;
	nMotorEncoder[mUp]= 0;
	while ( nMotorEncoder[mBuck]<14800)
	{
		motor[mBuck] = 100;
	}
	motor[mBuck] = 0 ;
}
