#pragma config(Motor,  motorA,          mUp,           tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB,          mBuck,         tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	nMotorEncoder[mBuck]= 0 ;
	nMotorEncoder[mUp]= 0;
	while ( nMotorEncoder[mUp]<3000)
	{
		motor[mUp] = 100;
	}
	motor[mUp] = 0 ;
}
