
#pragma config(Motor,  motorA,          mUp,           tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB,          mBuck,         tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          mTurn,         tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
task main()
{
while ( nMotorEncoder[mBuck]<400)
	{
		motor[mBuck] = 100;
	}
	motor[mBuck] = 0 ;
	nMotorEncoder[mBuck]= 0 ;
	nMotorEncoder[mUp]= 0;
	while ( nMotorEncoder[mUp]>-6500)
	{
		motor[mUp] = -6500;
	}
	motor[mUp] = 0 ;
		while (nMotorEncoder[mTurn] <  500)
	{
		motor[mTurn] = 100;
	}
}
