#pragma config(Sensor, S4,     sSonar,         sensorSONAR)
#pragma config(Motor,  motorA,          mA,            tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB,          mLeft,         tmotorNXT, PIDControl, reversed, encoder)
#pragma config(Motor,  motorC,          mRight,        tmotorNXT, PIDControl, reversed, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//int const disToApp = 10;
int initDist = 0;

bool isAppleHere();



task main()
{
	while (nMotorEncoder[mA]<580)
			{
				motor[mA]=100;
			}
			motor[mA] = 0;
			sleep(10000);
	initDist = SensorValue[sSonar];

	while (true)
	{
		if (isAppleHere())
		{
			playSound(soundBeepBeep);
			nMotorEncoder[mA]=0;
			//-----------------------------------
			while (nMotorEncoder[mA]>-580)
			{
				motor[mA]=-100;
			}
			motor[mA] = 0;
				nMotorEncoder[mLeft]=0;
			//------------------------------------
				while (nMotorEncoder[mLeft]<400)
			{
				motor[mLeft]=40;
				motor[mRight]=40;
			}
				motor[mLeft]=0;
			motor[mRight]=0;
			//motor[mLeft]=0;
			nMotorEncoder[mLeft]=0;
			//-------------------------------------
			/*while (nMotorEncoder[mLeft]<900)
			{
				motor[mLeft]=40;
				motor[mRight]=10;
			}
			motor[mLeft]=0;
			motor[mRight]=0;
			//motor[mLeft]=0;
			nMotorEncoder[mLeft]=0;
			//-----------------------------------
				while (nMotorEncoder[mLeft]<500)
			{
				motor[mLeft]=40;
				motor[mRight]=40;
			}
				motor[mLeft]=0;
			motor[mRight]=0;
			//motor[mLeft]=0;
			nMotorEncoder[mLeft]=0;
			//-------------------------------------
			*/
			break;
		}
		sleep(500);
	}
}
//*******************************************************************
bool isAppleHere()
{
	const int gap = 1;
	int sen = SensorValue[sSonar]	;
	displayTextLine(4,"%d",sen);
	if ((sen + gap < initDist ) || ( sen - gap > initDist ))
	{
		sleep(1000);
		sen = SensorValue[sSonar]	;
		if ((sen + gap < initDist ) || ( sen - gap > initDist )) return true;
	}
	return false;
}
