#pragma config(Sensor, S1,     sSonar,         sensorSONAR)
#pragma config(Motor,  motorA,          mA,            tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB,          mB,            tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          mC,            tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
int apple = 0;
int const disToApp = 10;
int sen = 0;
task apples()
{
	while(true)
	{
		sen = SensorValue[sSonar]
		displayTextLine(4,"%d",sen);
		displayTextLine(5,"%d",apple);
		if (SensorValue[sSonar]< disToApp)
		{
			apple = 1;
		}
		else
		{
			apple = 0;
		}
	}
}
task main()
{
	startTask(apples);
	if (apple == 1)
	{
		nMotorEncoder[mA]=0;
		while (nMotorEncoder[mA]<580)
		{
			motor[mA]=100;
		}
		motor[mA] = 0;
		nMotorEncoder[mB]=0;
		while (nMotorEncoder[mB]<580)
		{
			motor[mB]=50;
			motor[mC]=50;
		}
	}
}
