#pragma config(Sensor, S1,     sSonar,         sensorSONAR)
#pragma config(Motor,  motorA,          mA,            tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB,          mLeft,            tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          mRight,            tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
int const disToApp = 10;
int initDist = 0;

bool isAppleHere();

bool isAppleHere()
{
	const int gap = 1;
	int sen = SensorValue[sSonar]	;
	displayTextLine(4,"%d",sen);
	if ((sen + gap < initDist ) || ( sen - gap > initDist ))
	{
		sleep(1000);
		sen = SensorValue[sSonar]	;
		if ((sen + gap < initDist ) || ( sen - gap > initDist )) return true;
	}
	return false;
}

task main()
{
	initDist = SensorValue[sSonar];

	while (true)
	{
		if (isAppleHere())
		{
			playSound(soundBeepBeep);
			nMotorEncoder[mA]=0;
			while (nMotorEncoder[mA]<580)
			{
				motor[mA]=100;
			}
			motor[mA] = 0;
			nMotorEncoder[mLeft]=0;
			while (nMotorEncoder[mLeft]<500)
			{
				motor[mLeft]=50;
				motor[mRight]=50;
			}
			motor[mLeft]=0;
			motor[mRight]=0;
			break;
		}
		sleep(500);
	}
}
