#pragma config(Sensor, S1,     sLeft,    sensorEV3_GenericI2C)
#pragma config(Sensor, S2,     sIr1,           sensorEV3_IRSensor)
#pragma config(Sensor, S3,     sDis,           sensorEV3_Ultrasonic)
#pragma config(Sensor, S4,     sIr2,           sensorEV3_IRSensor)
#pragma config(Motor,  motorA,          mA,            tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorB,          mB,            tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorC,          mOut,          tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorD,          mDoor,         tmotorEV3_Medium, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
#include "mindsensors-irdist.h"

int getMedian();
task main()
{

	//int a[2];
	int b=getMedian();
	//a[1] = 121;
	displayTextLine(1,"%d",b);
	sleep(5000);


}
int getMedian()
{
	int a[5]
	a[0] = 1000;//MSDISTreadDist(sLeft);
	sleep(100);
	a[1] = 0;//MSDISTreadDist(sLeft);
	sleep(100);
	a[2] = 11;//MSDISTreadDist(sLeft);
	sleep(100);
	a[3] = 12;//MSDISTreadDist(sLeft);
	sleep(100);
	a[4] = 11;//MSDISTreadDist(sLeft);
	sleep(100);
	int flag = 1
	//int c = 0
	while (flag)
	{
	  flag = 0;
		for (int i; i < 4; i++)
		{

			if (a[i]>a[i+1])
			{
				int old = a[i];
				a[i]  = a[i+1] ;
				a[i+1] = old;
				flag = 1;
			}
		}
	}
	return a[2];//3
	//dv = MSDISTreadDist(sLeft);
	//errDist = abs(sort()-GoodDist);
}
