#pragma config(Sensor, S1,     sFrontRight,    sensorEV3_GenericI2C)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "mindsensors-irdist.h"
task main()
{
	int Dv = 0;
	int STOL = MSDISTreadDist(sFrontRight);
	sleep(100);
	while(true)
	{
		Dv = MSDISTreadDist(sFrontRight);
		displayTextLine(1, "%d", Dv);
		sleep(100);
	}
}
