#pragma config(Sensor, S1,     sIr,            sensorEV3_IRSensor, modeEV3IR_Seeker)
#pragma config(Sensor, S4,     sIr2,           sensorEV3_IRSensor, modeEV3IR_Seeker)
#pragma config(Motor,  motorA,          mA,            tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorB,          mB,            tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{

	int u = 0;
	float k = 0.3;
	int e = 0;
	const int v1 =50;

while (true)
		{

			e =	getIRBeaconChannelDirection(sIr2, 1);
			u = 6*e;
			displayTextLine(4, "%d",e);

			motor[mB]= -1 * (v1-u)*k;
			motor[mA]= -1 * (v1+u)*k;
			sleep(10);
			//readSensor(&muxedSensor[0]);
		}

}
