#pragma config(Sensor, S1,     sIr,            sensorNone)
#pragma config(Sensor, S2,     sDis,           sensorEV3_IRSensor)
#pragma config(Sensor, S3,     sApple,         sensorSONAR)
#pragma config(Sensor, S4,     sDis2,          sensorEV3_IRSensor)
#pragma config(Motor,  motorA,          mA,            tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorB,          mB,            tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorC,          mOut,          tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorD,          mDoor,         tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{



}
