#pragma config(Sensor, S1,     sIr,            sensorNone)
#pragma config(Sensor, S2,     sDis,           sensorNone)
#pragma config(Sensor, S3,     sApple,         sensorSONAR)
#pragma config(Sensor, S4,     sDis2,          sensorEV3_IRSensor)
#pragma config(Motor,  motorA,          mA,            tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorB,          mB,            tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorC,          mOut,          tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorD,          mDoor,         tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int e = 0;
int u = 0;
int const k1 = -1;
int it = 0;
int const distocon = 10;
int apple = 0; //apple check: 0-no apple, 1- apple
int disS = 0;
int disS2 = 0;
//int n = 0;//distance check flag: 0- stop, 1 - go, 2 - go back
int const v1 = 50; // speed main
//int	const v2 = 30; // speed slow
int const dis2 = 10 ;//distance to collector min
int const dis1 = 20;//distance to collector max
int const disA = 10;
float const k = 0.3;//slow speed value


int getBeacon()
{
	setSensorMode(sIr, modeEV3IR_Seeker);
	e =	getIRBeaconChannelDirection(sIr, 0);
	sleep(10);
	e =	getIRBeaconChannelDirection(sIr, 0);
	u = 6*e;
	return e;
	/*
	motor[mB]= (v1-u)*n*k;
	motor[mA]= (v1+u)*n*k;
	sleep(1);
	*/
}


int getDistance()
{
	/*
	if (apple ==0)
	{
		}
	else
	*/

	int n;

	setSensorMode(sIr,modeEV3IR_Proximity);
	disS = SensorValue[sIr];
	sleep(10);
	disS = SensorValue[sIr];

	displayTextLine(6,"%d",disS);
	if(SensorValue[sIr]<dis1)
	{
		if (SensorValue[sIr]<dis2)
		{
			n = 2;
		}
		else
		{
			n = 0;
		}
	}
	else
	{
		n = 1;
	}
	return n;
}
task main()
{

	while (true)
	{
		displayTextLine(4, "%d", getBeacon());
		sleep(100);
		displayTextLine(5, "%d", getDistance());
		//distance();

	}
}
