#pragma config(Motor,  motorA,          mSshat,        tmotorEV3_Medium, PIDControl, encoder)
#pragma config(Motor,  motorB,          mGnil,         tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          mDver,         tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorD,           ,             tmotorEV3_Large, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


int sshat = 0;

void dver()
{
	while (nMotorEncoder[mDver] > -140)// nado proverit
	{
		motor[mDver]=-30;

	}
	nMotorEncoder[mGnil]=0;
	nMotorEncoder[mSshat]=0;
	nMotorEncoder[mDver]=0;
	while (nMotorEncoder[mSshat] < 140)// nado proverit
	{
		motor[mDver]=-30;
	}
}

void encoder ()
{

	nMotorEncoder[mGnil]=0;
	nMotorEncoder[mSshat]=0;
	nMotorEncoder[mDver]=0;
}


void Gnil ()

{
	while (nMotorEncoder[mGnil] < 50)
	{
		motor[mGnil]=30;
	}

	while (nMotorEncoder[mSshat] < 140)
	{
		motor[mSshat]=30;
	}
	nMotorEncoder[mGnil]=0;
	nMotorEncoder[mSshat]=0;
	nMotorEncoder[mDver]=0;

	while (nMotorEncoder[mGnil] > -45)
	{
		motor[mGnil]=-30;
	}
	while (nMotorEncoder[mSshat] > -140)
	{
		motor[mSshat]=-30;

	}
	nMotorEncoder[mGnil]=0;
	nMotorEncoder[mSshat]=0;
	nMotorEncoder[mDver]=0;

}

void sshatie ()
{
	nMotorEncoder[mSshat]=0;
	motor[mSshat]=30;
	wait1Msec(2000);


	int sshat = nMotorEncoder[mSshat];

	nMotorEncoder[mSshat]=0;
	motor[mSshat]=-30;
	wait1Msec(2000);
}

task main()
{
	encoder () ;
	sshatie () ;
	if (sshat>160)
	{
		Gnil () ;
	}
	else
	{
		dver () ;
	}


}
