#pragma config(Sensor, S1,     sSvet,          sensorEV3_Touch)
#pragma config(Motor,  motorA,          mCon,          tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB,          mSort,         tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          mDver,         tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorD,           ,             tmotorEV3_Large, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task con()
{
	while (true)
	{
		motor[mCon]= 20;
	}
}

void dver()
{
	while (nMotorEncoder[mDver] < 100)
	{
		motor[mDver]=30;

	}
	motor[mDver]=0 ;
	nMotorEncoder[mDver]=0;

}


task main()
{
	startTask (con);

	int color = 0;
	while (SensorValue[sSvet]<=0)// dlya testa
	{
		wait1Msec(10);
	}
	wait1Msec(1000);
	if (SensorValue[sSvet] > 0)
	{
		color = 1	;

		nMotorEncoder[mSort]=0;
		while (nMotorEncoder[mSort] > -53)
		{
			motor[mSort]=-30;
		}
		motor[mSort]=0;
		dver ();
	}
	else
	{
		dver ();
	}

	displayTextLine(4, "%d", color);




}
